package com.sdk.customtasks.scriptreader.html;

/**
 * This Class is used to hold the style sheet constants for the HTML Output.
 * 
 * @author lkandasa
 *
 */
public class HtmlCssConstants {
	public static final String css = "/*\n" + "* multi-line comment\n" + "*/\n" + "p{ \n" + "line-height: 1em; \n"
			+ "}\n" + "h1, h2, h3, h4{\n" + "color: orange;\n" + "font-weight: normal;\n" + "line-height: 1.1em;\n"
			+ "margin: 0 0 .5em 0;\n" + "}\n" + "h1{\n" + "font-size: 1.7em; \n" + "}\n" + "h2{ \n"
			+ "font-size: 1.5em; \n" + "}\n" + "a{\n" + "color: black;\n" + "text-decoration: none;\n" + "}\n"
			+ "a:hover,\n" + "a:active{ \n" + "text-decoration: underline; \n" + "}\n" + ".title{\n"
			+ "text-align:center;\n" + "}\n"
			+ "/* you can structure your code's white space so that it is as readable for when you come back in the future or for other people to read and edit quickly */\n"
			+ "body{\n" + "font-family: arial; \n" + "font-size: 80%; \n" + "width: 100%; \n" + "margin: 0;\n"
			+ "background: #eee;\n" + "/*background-color:#36CCE3; //blue*/\n" + "background-color:#E6E6B8;\n" + "}\n"
			+ "#PageTitle \n" + "{\n" + "font-family: arial; font-size: 200%;\n" + "text-align:Center;\n" + "}\n"
			+ "#header {\n" + "background-color:black;\n" + "color:white;\n" + "text-align:center;\n" + "padding:5px;\n"
			+ "}\n" + "/* you can put your code all in one line like above */\n" + "#page{ \n" + "margin: 20px; \n"
			+ "}\n" + "/* or on different lines like below */\n" + "#logo{\n" + "width: 35%;\n" + "margin-top: 5px;\n"
			+ "font-family: georgia;\n" + "display: inline-block;\n" + "}\n" + "\n" + "#content{\n"
			+ "margin: 30px 0;\n" + "background: #E6E6B8;\n" + "padding: 20px;\n" + "clear: both;\n"
			+ "-webkit-border-radius: 50px;\n" + "-moz-border-radius: 50px;\n" + "border-radius: 50px;\n"
			+ "border:3px solid #000000;\n" + "border-radius:8px;\n" + "box-shadow:rgba(0,0,0,0.5) 0px 0px 24px;\n"
			+ "border-radius:12px;\n" + "\n" + "}\n" + "#footer{\n" + "border-bottom: 1px #ccc solid;\n"
			+ "margin-bottom: 10px;\n" + "}\n" + "#footer p{\n" + "text-align: right;\n"
			+ "text-transform: uppercase;\n" + "font-size: 80%;\n" + "color: grey;\n" + "}\n"
			+ "/* multiple styles seperated by a , */\n" + "\n" + "section {\n"
			+ "/* position is static by default */\n" + "margin-left: 200px;\n" + "}\n" + "#row { \n"
			+ "display: table-row; \n" + "}\n" + ".Table\n" + "{\n" + "display: table;\n" + "margin:auto;\n" + "}\n"
			+ ".Title\n" + "{\n" + "display: table-caption;\n" + "text-align: center;\n" + "font-weight: bold;\n"
			+ "font-size: larger;\n" + "\n" + "}\n" + ".Heading\n" + "{\n" + "display: table-row;\n"
			+ "font-weight: bold;\n" + "text-align: center;\n" + "background-color: #7A0000;\n" + "\n" + "}\n"
			+ ".Heading   .Cell p{\n" + "color: #FFFFFF;\n" + "}\n" + ".Row\n" + "{\n" + "display: table-row;\n" + "}\n"
			+ ".Cell\n" + "{\n" + "display: table-cell;\n" + "border: solid;\n" + "border-width: thin;\n"
			+ "padding-left: 5px;\n" + "padding-right: 5px;\n" + "}\n" + "#square {\n" + "width: auto;\n"
			+ "height: auto;\n" + "background-color: #FFC0CB;\n" + "}\n" + "#outerbox {\n" + "padding-left: 5px;\n"
			+ "padding-right: 5px;     \n" + "padding-bottom: 5px;        \n" + "background-color: #fff;\n"
			+ "border: 1px solid #000;\n" + "width: 100%;\n" + "}\n" + ".innerBox {\n" + "padding: 0px 10px 0px 10px;\n"
			+ "margin: 0px;\n" + "border: 1px solid #000;\n" + "}\n" + ".roundedcorners {\n" + "height: auto;\n"
			+ "width: auto;\n" + "border-radius: 40px;\n" + "border: 1px solid;\n" + "overflow: hidden;\n"
			+ "line-height:auto;\n" + "-webkit-border-radius: 50px;\n" + "-moz-border-radius: 50px;\n"
			+ "border-radius: 50px;\n" + "border:3px solid #999;\n" + "box-shadow:rgba(0,0,0,0.5) 0px 0px 24px;\n"
			+ "text-align:center;\n" + "}\n" + ".roundedcorners p {\n" + "font-size: 20pt;\n" + "font-style: bold;\n"
			+ "padding: 5px;\n" + "color:#7A0000;\n" + "}\n" + "\n" + "#reportpath{\n" + "border:3px solid #999;\n"
			+ "padding:1em;\n" + "-moz-border-radius:8px;\n" + "-webkit-border-radius:8px;\n"
			+ "-opera-border-radius:8px;\n" + "-khtml-border-radius:8px;\n" + "border-radius:8px;\n"
			+ "box-shadow:rgba(0,0,0,0.5) 0px 0px 24px;\n" + "border-radius:12px;\n" + "}\n" + "#reportPathTitle{\n"
			+ "font-size: 20pt;\n" + "padding: 5px;\n" + "text-align:center;\n" + "color:#7A0000;\n" + "}\n" + "\n"
			+ ".path{\n" + "font-size: 16pt;\n" + "}\n"+".roundedcorners {"+"\n"
			+"height:auto;"+"\n"
			+"width:auto;"+"\n"
			+"background:#AED6F1;"+"\n"
			+"overflow:hidden;"+"\n"
			+"line-height:auto;"+"\n"
			+"-webkit-border-radius:50px;"+"\n"
			+"-moz-border-radius:50px;"+"\n"
			+"border-radius:50px;"+"\n"
			+"border:3px solid #999;"+"\n"
			+"box-shadow:rgba(0,0,0,0.5) 0 0 24px;"+"\n"
			+"text-align:center;"+"\n"
			+"}"+"\n"
			+""+"\n"
			+".roundedcorners p {"+"\n"
			+"font-size:20pt;"+"\n"
			+"font-style:bold;"+"\n"
			+"padding:5px;"+"\n"
			+"}"+"\n"
			+""+"\n"
			
			+""+"\n"
			+".gridheader,.gridheaderbig,.gridheaderleft,.gridheaderright {"+"\n"
			+"background:#fff repeat-x;"+"\n"
			+"text-align:center;"+"\n"
			+"font-weight:700;"+"\n"
			+"text-decoration:none;"+"\n"
			+"border:solid 2px #1F618D;"+"\n"
			+"padding:4px;"+"\n"
			+"}"+"\n"
			+""+"\n"
			+".gridheader a,.gridheaderbig a {"+"\n"
			+"color:#FFF8DC;"+"\n"
			+"text-decoration:none;"+"\n"
			+"}"+"\n"
			+""+"\n"
			+".gridheaderleft {"+"\n"
			+"text-align:left;"+"\n"
			+"}"+"\n"
			+""+"\n"
			+".gridheaderright {"+"\n"
			+"text-align:right;"+"\n"
			+"}"+"\n"
			+""+"\n"
			+".gridheaderbig {"+"\n"
			+"font-size:135%;"+"\n"
			+"}"+"\n"
			+""+"\n"
			+".gridnormal {"+"\n"
			+"background-color:#eee;"+"\n"
			+"}"+"\n"
			+""+"\n"
			+".gridalternate {"+"\n"
			+"background-color:#b5c7d6;"+"\n"
			+"}"+"\n"
			+""+"\n"
			+".gridhighlight {"+"\n"
			+"background-image:url(images/LightOrangeGradient.png);"+"\n"
			+"background-repeat:repeat-x;"+"\n"
			+"background-color:#FFF;"+"\n"
			+"cursor:pointer;"+"\n"
			+"}"+"\n"
			+""+"\n";

}
